[build-system]
requires = [
    "setuptools >= 42",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pyright]
include = [
 "huantong_learning_proj",
]
# reportGeneralTypeIssues = false
# typeCheckingMode = "strict"
