CREATE TABLE `ORGALIAS` (
  `id` decimal(65,30) NOT NULL COMMENT 'PK',
  `organization_id` decimal(65,30) DEFAULT NULL COMMENT '标准机构ID',
  `ORGCODE` varchar(64) DEFAULT NULL COMMENT '标准机构CODE',
  `org_name` varchar(256) DEFAULT NULL COMMENT '标准机构名称',
  `name` varchar(325) DEFAULT NULL COMMENT '曾用名',
  `SPLITSTATUS` char(12) DEFAULT NULL COMMENT '拆词标记',
  `KEYWORD01` varchar(128) DEFAULT NULL COMMENT '拆词结果：省份',
  `KEYWORD02` varchar(128) DEFAULT NULL COMMENT '拆词结果：城市',
  `KEYWORD03` varchar(128) DEFAULT NULL COMMENT '拆词结果：区县',
  `KEYWORD04` varchar(128) DEFAULT NULL COMMENT '拆词结果：关键词4',
  `KEYWORD05` varchar(128) DEFAULT NULL COMMENT '拆词结果：关键词5',
  `KEYWORD06` varchar(128) DEFAULT NULL COMMENT '拆词结果：关键词6',
  `KEYWORD07` varchar(128) DEFAULT NULL COMMENT '拆词结果：关键词7',
  `KEYWORD08` varchar(128) DEFAULT NULL COMMENT '拆词结果：关键词8',
  `created_at` datetime DEFAULT NULL COMMENT '创建时间',
  `USERID` decimal(10,0) DEFAULT NULL COMMENT '操作人',
  `AREADUALFLAG` decimal(1,0) DEFAULT NULL COMMENT '是否已用函数解析省市区',
  `WORDCOUNT` decimal(2,0) DEFAULT NULL,
  `WORDCOUNTTIME` datetime DEFAULT NULL,
  `KEYWORD09` varchar(128) DEFAULT NULL COMMENT '拆词结果：关键词9',
  `KEYWORD10` varchar(128) DEFAULT NULL COMMENT '拆词结果：关键词10',
  `KEYWORD11` varchar(128) DEFAULT NULL COMMENT '拆词结果：关键词11:小写数字',
  `KEYWORD12` varchar(128) DEFAULT NULL COMMENT '拆词结果：关键词12:大写数字',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '自动更新时间',
  PRIMARY KEY (`id`),
  KEY `IDX_ALIASNAME` (`name`) USING BTREE,
  KEY `IDX_ORGID` (`organization_id`) USING BTREE,
  KEY `IDX_UPDATETIME` (`updated_at`) USING BTREE
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COMMENT='机构曾用名表';
